/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "AppClientLink": {
      "clientId": string
      "type": "sst.sst.Linkable"
    }
    "Config": {
      "rootDomainName": string
      "type": "sst.sst.Linkable"
    }
    "DnsTrigger": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Email": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "EmailTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Ipv6Proxy": {
      "domainName": string
      "type": "sst.sst.Linkable"
    }
    "MountPath": {
      "path": string
      "type": "sst.sst.Linkable"
    }
    "MountTargetIp": {
      "ip": string
      "type": "sst.sst.Linkable"
    }
    "Oidc": {
      "authSecret": string
      "clientId": string
      "clientSecret": string
      "issuer": string
      "redirectUri": string
      "scopes": string
      "type": "sst.sst.Linkable"
    }
    "SiteFunction": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "SiteRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "SiteStaticAssets": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "TargetRegion": {
      "name": string
      "type": "sst.sst.Linkable"
    }
    "UserPoolLink": {
      "type": "sst.sst.Linkable"
      "userPoolId": string
    }
    "VanillaAddFileLambda": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Vpc": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
  }
}
